/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfacevisual;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author detup
 */
public class EditarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form EditarUsuario
     */
    public void setconfpanel(JPanel p){
        p.setSize(1024,1024);
        p.setLocation(0,0 ); // setlocation 0 p ser no meio da tela
        EditarUsuarioPanel.add(p);
        EditarUsuarioPanel.revalidate();
        EditarUsuarioPanel.repaint();
    }
    public EditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        EditarUsuarioPanel = new javax.swing.JPanel();
        novoNomeUsuario = new javax.swing.JFormattedTextField();
        novoEmailUsuario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        editarUsuarioButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1024, 1024));

        EditarUsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));
        EditarUsuarioPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        EditarUsuarioPanel.setName(""); // NOI18N
        EditarUsuarioPanel.setPreferredSize(new java.awt.Dimension(1024, 1024));

        novoNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoNomeUsuarioActionPerformed(evt);
            }
        });

        novoEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEmailUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Novo Nome");

        editarUsuarioButton.setBackground(new java.awt.Color(0, 102, 204));
        editarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editarUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        editarUsuarioButton.setText("Editar");
        editarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Novo E-mail");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Editar Usuário");

        javax.swing.GroupLayout EditarUsuarioPanelLayout = new javax.swing.GroupLayout(EditarUsuarioPanel);
        EditarUsuarioPanel.setLayout(EditarUsuarioPanelLayout);
        EditarUsuarioPanelLayout.setHorizontalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditarUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoNomeUsuario)
                    .addComponent(novoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(350, 350, 350))
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(editarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditarUsuarioPanelLayout.setVerticalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(editarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EditarUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void novoEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void novoNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void editarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        if(novoEmailUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Nome Invalido!");
        }else if(novoNomeUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Email Invalido!");
        }else{
            Usuarios layoutusuario = new Usuarios();
            JOptionPane.showMessageDialog(null,"Editado com Sucesso!");
            layoutusuario.setNovoEmail(novoEmailUsuario.getText()); 
            layoutusuario.setNovoNome(novoNomeUsuario.getText());
            layoutusuario.editTable();
            EditarUsuarioPanel.removeAll();
            setconfpanel(layoutusuario);   
        }
    }                                                   


    // Variables declaration - do not modify                     
    private javax.swing.JPanel EditarUsuarioPanel;
    public javax.swing.JButton editarUsuarioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JFormattedTextField novoEmailUsuario;
    public javax.swing.JFormattedTextField novoNomeUsuario;
    // End of variables declaration                   
}
